name: vsix

on:
  push:
    branches: [main, trying, staging]
  pull_request:
    branches: [main]

jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Move ci tag
        uses: weareyipyip/walking-tag-action@master
        with:
          tag-name: nightly-build
          tag-message: |
            Last commit build by the CI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        if: github.ref == 'refs/heads/main'

  build:
    needs: [move-tag]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16.x
    - name: Setup pnpm for sane package management
      uses: pnpm/action-setup@v2.2.2
    - name: Build
      run: pnpm i
    - name: Install vsce
      run: pnpm i -g vsce
    - name: Build vsix
      run: pnpm package
    - uses: actions/upload-artifact@v2
      with:
        name: aya-prover-vscode-extension
        path: ./aya-prover-vscode-*.vsix
    
    - run: cp -a ./aya-prover-vscode-*.vsix ./aya-prover-vscode-nightly.vsix

    - name: Update the CI tag
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        isPrerelease: false
        tag_name: nightly-build
        release_name: "Automatic CI builds"
        body_mrkdwn: |
          _This is the newest build, but Github date can't be updated. Corresponding commit: ${{ github.sha }}_
        assets: ./aya-prover-vscode-nightly.vsix|application/zip
        replace_assets: true
        github_token: ${{ secrets.GH_TOKEN }}
      if: github.ref == 'refs/heads/main'
