name: vsix

on:
  push:
    branches: [main, trying, staging]
  pull_request:
    branches: [main]

jobs:
  move-tag :
    runs-on : ubuntu-latest
    steps :
      - name : Move ci tag
        run : |
          mkdir repo
          git clone -b "$BRANCH_NAME" "https://github.com/${GITHUB_REPOSITORY}" repo
          cd repo
          bash .github/workflows/move-tag.sh "nightly-build" "Last commit build by the CI"
        env :
          GITHUB_TOKEN : ${{ secrets.GH_TOKEN }}
          BRANCH_NAME : ${{ github.head_ref || github.ref_name }}

  build:
    needs: [move-tag]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - uses: lannonbr/vsce-action@master
      with:
        args: "package"
    - uses: actions/upload-artifact@v2
      with:
        name: aya-prover-vscode-extension
        path: ./aya-prover-vscode-*.vsix
    
    - run: cp -a ./aya-prover-vscode-*.vsix ./aya-prover-vscode-nightly.vsix

    - name: Publish Nightly Build
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        isPrerelease: false
        tag_name: nightly-build
        release_name: "Nightly builds"
        body_mrkdwn: |
          _These are latest builds, but the date on GitHub is frozen due to stupid limitations.
          Corresponding commit: ${{ github.sha }}_
        assets: ./aya-prover-vscode-nightly.vsix|application/zip
        replace_assets: true
        github_token: ${{ secrets.GH_TOKEN }}
      if: github.ref == 'refs/heads/main'
